services:
  martin:
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      target: prod
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      target: prod
    restart: unless-stopped
