/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/schools/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Schools Stream */
        get: operations["read_schools_stream_api_v1_schools_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schools/{school_id}/short": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read School Short */
        get: operations["read_school_short_api_v1_schools__school_id__short_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schools/{school_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read School */
        get: operations["read_school_api_v1_schools__school_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schools/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Schools
         * @description Get schools with optional filters.
         *
         *     _**Note:**
         *     This endpoint should only be used for smaller amounts of data. To get all schools consider using `/school/stream` endpoint with StreamingResponse._
         *
         *     ## Filter Logic
         *     - Filters are combined with AND logic between different filter types
         *     - Multiple values within the same filter use OR logic
         *     - Example: `type=1&typeid=2&status=1` means
         *       (type 1 OR type 2) AND (status 1)
         */
        get: operations["read_schools_api_v1_schools__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/filters/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Filters */
        get: operations["read_filters_api_v1_filters__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/school_types/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read School Types
         * @description Fetch all available school types or school types filtered by a list of names.
         */
        get: operations["read_school_types_api_v1_school_types__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/school_types/{school_type_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read School Type
         * @description Fetch a single school type by its ID.
         */
        get: operations["read_school_type_api_v1_school_types__school_type_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rankings/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Rankings Filters */
        get: operations["read_rankings_filters_api_v1_rankings_filters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rankings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Rankings */
        get: operations["read_rankings_api_v1_rankings__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root_test_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** EtapEdukacjiPublic */
        EtapEdukacjiPublic: {
            /** Nazwa */
            nazwa: string;
            /** Id */
            id: number;
        };
        /** FiltersResponse */
        FiltersResponse: {
            /** School Types */
            school_types: components["schemas"]["TypSzkolyPublic"][];
            /** Public Statuses */
            public_statuses: components["schemas"]["StatusPublicznoprawnyPublic"][];
            /** Student Categories */
            student_categories: components["schemas"]["KategoriaUczniowPublic"][];
            /** Vocational Training */
            vocational_training: components["schemas"]["KsztalcenieZawodowePublic"][];
        };
        /** GminaPublicWithPowiat */
        GminaPublicWithPowiat: {
            /** Nazwa */
            nazwa: string;
            /** Teryt */
            teryt: string;
            /** Powiat Id */
            powiat_id: number;
            /** Id */
            id: number;
            powiat: components["schemas"]["PowiatPublicWithWojewodztwo"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** KategoriaUczniowPublic */
        KategoriaUczniowPublic: {
            /** Nazwa */
            nazwa: string;
            /** Id */
            id: number;
        };
        /** KsztalcenieZawodowePublic */
        KsztalcenieZawodowePublic: {
            /** Nazwa */
            nazwa: string;
            /** Id */
            id: number;
        };
        /** MiejscowoscPublic */
        MiejscowoscPublic: {
            /** Nazwa */
            nazwa: string;
            /** Teryt */
            teryt: string;
            /** Gmina Id */
            gmina_id: number;
            /** Id */
            id: number;
        };
        /** MiejscowoscPublicWithGmina */
        MiejscowoscPublicWithGmina: {
            /** Nazwa */
            nazwa: string;
            /** Teryt */
            teryt: string;
            /** Gmina Id */
            gmina_id: number;
            /** Id */
            id: number;
            gmina: components["schemas"]["GminaPublicWithPowiat"];
        };
        /** PowiatPublic */
        PowiatPublic: {
            /** Nazwa */
            nazwa: string;
            /** Teryt */
            teryt: string;
            /** Wojewodztwo Id */
            wojewodztwo_id: number;
            /** Id */
            id: number;
        };
        /** PowiatPublicWithWojewodztwo */
        PowiatPublicWithWojewodztwo: {
            /** Nazwa */
            nazwa: string;
            /** Teryt */
            teryt: string;
            /** Wojewodztwo Id */
            wojewodztwo_id: number;
            /** Id */
            id: number;
            wojewodztwo: components["schemas"]["WojewodztwoPublic"];
        };
        /** PrzedmiotPublic */
        PrzedmiotPublic: {
            /** Nazwa */
            nazwa: string;
            /** Id */
            id: number;
        };
        /**
         * RankingDirection
         * @enum {string}
         */
        RankingDirection: "BEST" | "WORST";
        /** RankingPublic */
        RankingPublic: {
            /** Rok */
            rok: number;
            rodzaj_rankingu: components["schemas"]["RodzajRankingu"];
            /** Wynik */
            wynik: number;
            /** Percentyl Kraj */
            percentyl_kraj: number;
            /** Miejsce Kraj */
            miejsce_kraj: number;
            /** Liczba Szkol Kraj */
            liczba_szkol_kraj: number;
            /** Percentyl Wojewodztwo */
            percentyl_wojewodztwo: number;
            /** Miejsce Wojewodztwo */
            miejsce_wojewodztwo: number;
            /** Liczba Szkol Wojewodztwo */
            liczba_szkol_wojewodztwo: number;
            /** Percentyl Powiat */
            percentyl_powiat: number;
            /** Miejsce Powiat */
            miejsce_powiat: number;
            /** Liczba Szkol Powiat */
            liczba_szkol_powiat: number;
            /** Szkola Id */
            szkola_id: number;
            /** Id */
            id: number;
        };
        /**
         * RankingScope
         * @enum {string}
         */
        RankingScope: "KRAJ" | "WOJEWODZTWO" | "POWIAT";
        /** RankingWithSchool */
        RankingWithSchool: {
            /** Rok */
            rok: number;
            rodzaj_rankingu: components["schemas"]["RodzajRankingu"];
            /** Wynik */
            wynik: number;
            /** Percentyl Kraj */
            percentyl_kraj: number;
            /** Miejsce Kraj */
            miejsce_kraj: number;
            /** Liczba Szkol Kraj */
            liczba_szkol_kraj: number;
            /** Percentyl Wojewodztwo */
            percentyl_wojewodztwo: number;
            /** Miejsce Wojewodztwo */
            miejsce_wojewodztwo: number;
            /** Liczba Szkol Wojewodztwo */
            liczba_szkol_wojewodztwo: number;
            /** Percentyl Powiat */
            percentyl_powiat: number;
            /** Miejsce Powiat */
            miejsce_powiat: number;
            /** Liczba Szkol Powiat */
            liczba_szkol_powiat: number;
            /** Szkola Id */
            szkola_id: number;
            /** Id */
            id: number;
            szkola: components["schemas"]["SzkolaRankingRow"];
        };
        /** RankingsFiltersResponse */
        RankingsFiltersResponse: {
            /** Years */
            years: number[];
            /** Scopes */
            scopes: components["schemas"]["RankingScope"][];
            /** Types */
            types: components["schemas"]["RodzajRankingu"][];
            /** Directions */
            directions: components["schemas"]["RankingDirection"][];
            /** Voivodeships */
            voivodeships: components["schemas"]["WojewodztwoPublic"][];
            /** Counties */
            counties: components["schemas"]["PowiatPublic"][];
        };
        /** RankingsResponse */
        RankingsResponse: {
            /**
             * Page
             * @description Current page number
             */
            page: number;
            /**
             * Pagesize
             * @description Number of items per page (can differ from requested page_size if fewer items are available)
             */
            pageSize: number;
            /**
             * Total
             * @description Total number of schools matching the ranking params criteria
             */
            total: number;
            /**
             * Totalpages
             * @description Total number of pages available based on the page_size
             */
            totalPages: number;
            /** Rankings */
            rankings: components["schemas"]["RankingWithSchool"][];
        };
        /**
         * RodzajRankingu
         * @enum {string}
         */
        RodzajRankingu: "E8" | "EM_LO" | "EM_TECH";
        /** StatusPublicznoprawnyPublic */
        StatusPublicznoprawnyPublic: {
            /** Nazwa */
            nazwa: string;
            /** Id */
            id: number;
        };
        /** SzkolaPublicShort */
        SzkolaPublicShort: {
            /** Nazwa */
            nazwa: string;
            /** Id */
            id: number;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Wynik */
            wynik: number | null;
            /** Typ */
            typ: string;
            /** Status */
            status: string;
        };
        /** SzkolaPublicWithRelations */
        SzkolaPublicWithRelations: {
            /** Nazwa */
            nazwa: string;
            /** Numerrspo */
            numerRspo: number;
            /** Nip */
            nip: string | null;
            /** Regon */
            regon: string | null;
            /** Liczbauczniow */
            liczbaUczniow: number | null;
            /** Dyrektorimie */
            dyrektorImie: string | null;
            /** Dyrektornazwisko */
            dyrektorNazwisko: string | null;
            /** Kodpocztowy */
            kodPocztowy: string | null;
            /** Numerbudynku */
            numerBudynku: string | null;
            /** Numerlokalu */
            numerLokalu: string | null;
            /** Telefon */
            telefon: string | null;
            /** Email */
            email: string | null;
            /** Stronainternetowa */
            stronaInternetowa: string | null;
            /** Datazalozenia */
            dataZalozenia: string | null;
            /** Datarozpoczecia */
            dataRozpoczecia: string | null;
            /** Datalikwidacji */
            dataLikwidacji: string | null;
            /** Wynik */
            wynik: number | null;
            /**
             * Zlikwidowana
             * @default false
             */
            zlikwidowana: boolean;
            /** Typid */
            typId: number;
            /** Statuspublicznoprawnyid */
            statusPublicznoprawnyId: number;
            /** Kategoriauczniowid */
            kategoriaUczniowId: number;
            /** Miejscowoscid */
            miejscowoscId: number;
            /** Ulicaid */
            ulicaId: number | null;
            /** Id */
            id: number;
            /** Etapyedukacji */
            etapyEdukacji: components["schemas"]["EtapEdukacjiPublic"][];
            typ: components["schemas"]["TypSzkolyPublic"];
            statusPublicznoprawny: components["schemas"]["StatusPublicznoprawnyPublic"];
            kategoriaUczniow: components["schemas"]["KategoriaUczniowPublic"];
            miejscowosc: components["schemas"]["MiejscowoscPublicWithGmina"];
            ulica: components["schemas"]["UlicaPublic"] | null;
            /** Ksztalceniezawodowe */
            ksztalcenieZawodowe: components["schemas"]["KsztalcenieZawodowePublic"][];
            /** Wynikie8 */
            wynikiE8: components["schemas"]["WynikE8PublicWithPrzedmiot"][];
            /** Wynikiem */
            wynikiEm: components["schemas"]["WynikEMPublicWithPrzedmiot"][];
            /** Rankingi */
            rankingi: components["schemas"]["RankingPublic"][];
        };
        /** SzkolaRankingRow */
        SzkolaRankingRow: {
            /** Nazwa */
            nazwa: string;
            /** Id */
            id: number;
            /** Numer Rspo */
            numer_rspo: number;
            status_publicznoprawny: components["schemas"]["StatusPublicznoprawnyPublic"];
            miejscowosc: components["schemas"]["MiejscowoscPublic"];
        };
        /** TypSzkolyPublic */
        TypSzkolyPublic: {
            /** Nazwa */
            nazwa: string;
            /** Id */
            id: number;
        };
        /** UlicaPublic */
        UlicaPublic: {
            /** Nazwa */
            nazwa: string;
            /** Teryt */
            teryt: string;
            /** Id */
            id: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WojewodztwoPublic */
        WojewodztwoPublic: {
            /** Nazwa */
            nazwa: string;
            /** Teryt */
            teryt: string;
            /** Id */
            id: number;
        };
        /** WynikE8PublicWithPrzedmiot */
        WynikE8PublicWithPrzedmiot: {
            /** Liczba Zdajacych */
            liczba_zdajacych: number | null;
            /** Mediana */
            mediana?: number | null;
            /** Wynik Sredni */
            wynik_sredni: number | null;
            /** Szkola Id */
            szkola_id: number;
            /** Przedmiot Id */
            przedmiot_id: number;
            /** Rok */
            rok: number;
            /** Id */
            id: number;
            przedmiot: components["schemas"]["PrzedmiotPublic"];
        };
        /** WynikEMPublicWithPrzedmiot */
        WynikEMPublicWithPrzedmiot: {
            /** Liczba Zdajacych */
            liczba_zdajacych: number | null;
            /** Mediana */
            mediana?: number | null;
            /** Sredni Wynik */
            sredni_wynik: number | null;
            /** Zdawalnosc */
            zdawalnosc?: number | null;
            /** Liczba Laureatow Finalistow */
            liczba_laureatow_finalistow?: number | null;
            /** Szkola Id */
            szkola_id: number;
            /** Przedmiot Id */
            przedmiot_id: number;
            /** Rok */
            rok: number;
            /** Id */
            id: number;
            przedmiot: components["schemas"]["PrzedmiotPublic"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_schools_stream_api_v1_schools_stream_get: {
        parameters: {
            query?: {
                minLng?: number | null;
                minLat?: number | null;
                maxLng?: number | null;
                maxLat?: number | null;
                bbox_mode?: "within" | "outside";
                /** @description Search query for school name */
                q?: string | null;
                /** @description Filter by school type IDs */
                type?: number[] | null;
                /** @description Filter by public/private status IDs */
                status?: number[] | null;
                /** @description Filter by student category IDs */
                category?: number[] | null;
                /** @description Filter by vocational training IDs */
                career?: number[] | null;
                min_score?: number | null;
                max_score?: number | null;
                /** @description Include closed/liquidated schools in the results */
                closed?: boolean;
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_school_short_api_v1_schools__school_id__short_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                school_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SzkolaPublicShort"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_school_api_v1_schools__school_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                school_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SzkolaPublicWithRelations"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_schools_api_v1_schools__get: {
        parameters: {
            query?: {
                minLng?: number | null;
                minLat?: number | null;
                maxLng?: number | null;
                maxLat?: number | null;
                bbox_mode?: "within" | "outside";
                /** @description Search query for school name */
                q?: string | null;
                /** @description Filter by school type IDs */
                type?: number[] | null;
                /** @description Filter by public/private status IDs */
                status?: number[] | null;
                /** @description Filter by student category IDs */
                category?: number[] | null;
                /** @description Filter by vocational training IDs */
                career?: number[] | null;
                min_score?: number | null;
                max_score?: number | null;
                /** @description Include closed/liquidated schools in the results */
                closed?: boolean;
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SzkolaPublicShort"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_filters_api_v1_filters__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FiltersResponse"];
                };
            };
        };
    };
    read_school_types_api_v1_school_types__get: {
        parameters: {
            query?: {
                /** @description Filter by school type names */
                names?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypSzkolyPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_school_type_api_v1_school_types__school_type_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                school_type_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypSzkolyPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_rankings_filters_api_v1_rankings_filters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingsFiltersResponse"];
                };
            };
        };
    };
    read_rankings_api_v1_rankings__get: {
        parameters: {
            query: {
                /** @description Requested page number */
                page?: number;
                /** @description Number of items per page (max 100) */
                pageSize?: number;
                year: number;
                /** @description Ranking type: E8 (primary schools), EM_LO (matura results - high schools), EM_TECH (matura results - technical schools) */
                type?: components["schemas"]["RodzajRankingu"];
                /** @description Ranking scope: KRAJ (national), WOJEWODZTWO (voivodeship), POWIAT (county) */
                scope?: components["schemas"]["RankingScope"];
                /** @description Ranking order: BEST (top schools first) or WORST (lowest schools first) */
                direction?: components["schemas"]["RankingDirection"];
                /** @description Required if scope is WOJEWODZTWO */
                voivodeshipId?: number | null;
                /** @description Required if scope is POWIAT */
                countyId?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root_test_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
