/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/schools/{school_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read School */
        get: operations["read_school_schools__school_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schools/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Schools
         * @description Get schools within bounding box with optional filters.
         *
         *     ## Filter Logic
         *     - Filters are combined with AND logic between different filter types
         *     - Multiple values within the same filter use OR logic
         *     - Example: `typ_id=1&typ_id=2&status_id=1` means
         *       (type 1 OR type 2) AND (status 1)
         */
        get: operations["read_schools_schools__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/school_types/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read School Types
         * @description Fetch all available school types or school types filtered by a list of names.
         */
        get: operations["read_school_types_school_types__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/school_types/{school_type_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read School Type By Id */
        get: operations["read_school_type_by_id_school_types__school_type_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/filters/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Filters */
        get: operations["read_filters_filters__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root_test_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** EtapEdukacjiPublic */
        EtapEdukacjiPublic: {
            /** Nazwa */
            nazwa: string;
            /** Id */
            id: number;
        };
        /** FiltersResponse */
        FiltersResponse: {
            /** School Types */
            school_types: components["schemas"]["TypSzkolyPublic"][];
            /** Public Statuses */
            public_statuses: components["schemas"]["StatusPublicznoprawnyPublic"][];
            /** Student Categories */
            student_categories: components["schemas"]["KategoriaUczniowPublic"][];
            /** Vocational Training */
            vocational_training: components["schemas"]["KsztalcenieZawodowePublic"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** KategoriaUczniowPublic */
        KategoriaUczniowPublic: {
            /** Nazwa */
            nazwa: string;
            /** Id */
            id: number;
        };
        /** KsztalcenieZawodowePublic */
        KsztalcenieZawodowePublic: {
            /** Nazwa */
            nazwa: string;
            /** Id */
            id: number;
        };
        /** MiejscowoscPublic */
        MiejscowoscPublic: {
            /** Nazwa */
            nazwa: string;
            /** Teryt */
            teryt: string;
            /** Gmina Id */
            gmina_id?: number | null;
            /** Id */
            id: number;
        };
        /** PrzedmiotPublic */
        PrzedmiotPublic: {
            /** Nazwa */
            nazwa: string;
            /** Id */
            id: number;
        };
        /** StatusPublicznoprawnyPublic */
        StatusPublicznoprawnyPublic: {
            /** Nazwa */
            nazwa: string;
            /** Id */
            id: number;
        };
        /** SzkolaPublicShort */
        SzkolaPublicShort: {
            /** Numer Rspo */
            numer_rspo: number;
            /** Nazwa */
            nazwa: string;
            /** Id */
            id: number;
            /** Geolokalizacja Latitude */
            geolokalizacja_latitude: number;
            /** Geolokalizacja Longitude */
            geolokalizacja_longitude: number;
            /** Score */
            score: number | null;
            typ: components["schemas"]["TypSzkolyPublic"];
            status_publicznoprawny: components["schemas"]["StatusPublicznoprawnyPublic"];
        };
        /** SzkolaPublicWithRelations */
        SzkolaPublicWithRelations: {
            /** Numer Rspo */
            numer_rspo: number;
            /** Nazwa */
            nazwa: string;
            /** Nip */
            nip?: string | null;
            /** Regon */
            regon: string;
            /** Liczba Uczniow */
            liczba_uczniow?: number | null;
            /** Dyrektor Imie */
            dyrektor_imie?: string | null;
            /** Dyrektor Nazwisko */
            dyrektor_nazwisko?: string | null;
            /** Kod Pocztowy */
            kod_pocztowy: string;
            /** Numer Budynku */
            numer_budynku?: string | null;
            /** Numer Lokalu */
            numer_lokalu?: string | null;
            /** Telefon */
            telefon?: string | null;
            /** Email */
            email?: string | null;
            /** Strona Internetowa */
            strona_internetowa?: string | null;
            /** Geolokalizacja Latitude */
            geolokalizacja_latitude: number;
            /** Geolokalizacja Longitude */
            geolokalizacja_longitude: number;
            /** Score */
            score?: number | null;
            /** Typ Id */
            typ_id?: number | null;
            /** Status Publicznoprawny Id */
            status_publicznoprawny_id?: number | null;
            /** Kategoria Uczniow Id */
            kategoria_uczniow_id?: number | null;
            /** Miejscowosc Id */
            miejscowosc_id?: number | null;
            /** Ulica Id */
            ulica_id?: number | null;
            /** Id */
            id: number;
            /**
             * Etapy Edukacji
             * @default []
             */
            etapy_edukacji: components["schemas"]["EtapEdukacjiPublic"][];
            typ: components["schemas"]["TypSzkolyPublic"];
            status_publicznoprawny: components["schemas"]["StatusPublicznoprawnyPublic"];
            kategoria_uczniow: components["schemas"]["KategoriaUczniowPublic"];
            miejscowosc: components["schemas"]["MiejscowoscPublic"];
            ulica: components["schemas"]["UlicaPublic"] | null;
            /** Ksztalcenie Zawodowe */
            ksztalcenie_zawodowe: components["schemas"]["KsztalcenieZawodowePublic"][];
            /** Wyniki E8 */
            wyniki_e8: components["schemas"]["WynikE8PublicWithPrzedmiot"][];
            /** Wyniki Em */
            wyniki_em: components["schemas"]["WynikEMPublicWithPrzedmiot"][];
        };
        /** TypSzkolyPublic */
        TypSzkolyPublic: {
            /** Nazwa */
            nazwa: string;
            /** Id */
            id: number;
        };
        /** UlicaPublic */
        UlicaPublic: {
            /** Nazwa */
            nazwa: string;
            /** Teryt */
            teryt: string;
            /** Id */
            id: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WynikE8PublicWithPrzedmiot */
        WynikE8PublicWithPrzedmiot: {
            /** Liczba Zdajacych */
            liczba_zdajacych: number | null;
            /** Mediana */
            mediana?: number | null;
            /** Wynik Sredni */
            wynik_sredni: number | null;
            /** Szkola Id */
            szkola_id: number;
            /** Przedmiot Id */
            przedmiot_id: number;
            /** Rok */
            rok: number;
            /** Id */
            id: number;
            przedmiot: components["schemas"]["PrzedmiotPublic"];
        };
        /** WynikEMPublicWithPrzedmiot */
        WynikEMPublicWithPrzedmiot: {
            /** Liczba Zdajacych */
            liczba_zdajacych: number | null;
            /** Mediana */
            mediana?: number | null;
            /** Sredni Wynik */
            sredni_wynik: number | null;
            /** Zdawalnosc */
            zdawalnosc?: number | null;
            /** Liczba Laureatow Finalistow */
            liczba_laureatow_finalistow?: number | null;
            /** Szkola Id */
            szkola_id: number;
            /** Przedmiot Id */
            przedmiot_id: number;
            /** Rok */
            rok: number;
            /** Id */
            id: number;
            przedmiot: components["schemas"]["PrzedmiotPublic"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_school_schools__school_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                school_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SzkolaPublicWithRelations"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_schools_schools__get: {
        parameters: {
            query?: {
                /** @description Search query for school name */
                q?: string | null;
                /** @description Filter by school type IDs */
                type?: number[] | null;
                /** @description Filter by public/private status IDs */
                status?: number[] | null;
                /** @description Filter by student category IDs */
                category?: number[] | null;
                /** @description Filter by vocational training IDs */
                vocational_training?: number[] | null;
                min_score?: number | null;
                max_score?: number | null;
                /**
                 * @description Bounding box: min_lng,min_lat,max_lng,max_lat
                 * @example 19.0,51.9,19.1,52.0
                 */
                bbox?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SzkolaPublicShort"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_school_types_school_types__get: {
        parameters: {
            query?: {
                /** @description Filter by school type names */
                names?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypSzkolyPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_school_type_by_id_school_types__school_type_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                school_type_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypSzkolyPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_filters_filters__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FiltersResponse"];
                };
            };
        };
    };
    root_test_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
