"""make foreign keys not null

Revision ID: 61773fb4d705
Revises: fff7ba934856
Create Date: 2026-02-08 23:53:04.567911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '61773fb4d705'
down_revision: Union[str, Sequence[str], None] = 'fff7ba934856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('szkola', 'typ_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('szkola', 'status_publicznoprawny_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('szkola', 'kategoria_uczniow_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('szkola', 'miejscowosc_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('szkola', 'miejscowosc_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('szkola', 'kategoria_uczniow_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('szkola', 'status_publicznoprawny_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('szkola', 'typ_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
