"""nullable geom in Szkola

Revision ID: 6eaa8b47a1e9
Revises: 947df3bbefc7
Create Date: 2026-02-15 11:56:18.319529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '6eaa8b47a1e9'
down_revision: Union[str, Sequence[str], None] = '947df3bbefc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('szkola', 'geom',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('szkola', 'geom',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True),
               nullable=False)
    # ### end Alembic commands ###
