"""add geom_3857 column

Revision ID: 764081c811b1
Revises: 02bea8fed6cd
Create Date: 2026-02-21 19:42:11.847256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '764081c811b1'
down_revision: Union[str, Sequence[str], None] = '02bea8fed6cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('szkola', sa.Column('geom_3857', geoalchemy2.types.Geometry(geometry_type='POINT', srid=3857, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('szkola', 'geom_3857')
    # ### end Alembic commands ###
