"""remove nazwa_skrocona column

Revision ID: 8b09b66e3ce4
Revises: 6eaa8b47a1e9
Create Date: 2026-02-15 20:01:50.000990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8b09b66e3ce4'
down_revision: Union[str, Sequence[str], None] = '6eaa8b47a1e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_szkola_nazwa_skrocona'), table_name='szkola')
    op.drop_column('szkola', 'nazwa_skrocona')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('szkola', sa.Column('nazwa_skrocona', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_szkola_nazwa_skrocona'), 'szkola', ['nazwa_skrocona'], unique=False)
    # ### end Alembic commands ###
