"""location foreign keys not null

Revision ID: 947df3bbefc7
Revises: 65521748b5cb
Create Date: 2026-02-09 08:48:50.982725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '947df3bbefc7'
down_revision: Union[str, Sequence[str], None] = '65521748b5cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gmina', 'powiat_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('miejscowosc', 'gmina_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('powiat', 'wojewodztwo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('powiat', 'wojewodztwo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('miejscowosc', 'gmina_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('gmina', 'powiat_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
