"""add Kontakt table

Revision ID: cd818eb49e59
Revises: 931733737e93
Create Date: 2026-02-23 15:32:16.828159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cd818eb49e59'
down_revision: Union[str, Sequence[str], None] = '931733737e93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kontakt',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=254), nullable=False),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('turnstile_token', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kontakt')
    # ### end Alembic commands ###
