"""init schema

Revision ID: db9f404de7d5
Revises: 
Create Date: 2026-02-02 18:45:41.132353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'db9f404de7d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etap_edukacji',
    sa.Column('nazwa', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etap_edukacji_nazwa'), 'etap_edukacji', ['nazwa'], unique=True)
    op.create_table('kategoria_uczniow',
    sa.Column('nazwa', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kategoria_uczniow_nazwa'), 'kategoria_uczniow', ['nazwa'], unique=True)
    op.create_table('ksztalcenie_zawodowe',
    sa.Column('nazwa', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ksztalcenie_zawodowe_nazwa'), 'ksztalcenie_zawodowe', ['nazwa'], unique=True)
    op.create_table('przedmiot',
    sa.Column('nazwa', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_przedmiot_nazwa'), 'przedmiot', ['nazwa'], unique=True)
    op.create_table('status_publicznoprawny',
    sa.Column('nazwa', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_publicznoprawny_nazwa'), 'status_publicznoprawny', ['nazwa'], unique=True)
    op.create_table('typ_szkoly',
    sa.Column('nazwa', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_typ_szkoly_nazwa'), 'typ_szkoly', ['nazwa'], unique=True)
    op.create_table('ulica',
    sa.Column('nazwa', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('teryt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ulica_nazwa'), 'ulica', ['nazwa'], unique=False)
    op.create_index(op.f('ix_ulica_teryt'), 'ulica', ['teryt'], unique=True)
    op.create_table('wojewodztwo',
    sa.Column('nazwa', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('teryt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wojewodztwo_nazwa'), 'wojewodztwo', ['nazwa'], unique=False)
    op.create_index(op.f('ix_wojewodztwo_teryt'), 'wojewodztwo', ['teryt'], unique=True)
    op.create_table('powiat',
    sa.Column('nazwa', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('teryt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('wojewodztwo_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['wojewodztwo_id'], ['wojewodztwo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_powiat_nazwa'), 'powiat', ['nazwa'], unique=False)
    op.create_index(op.f('ix_powiat_teryt'), 'powiat', ['teryt'], unique=True)
    op.create_index(op.f('ix_powiat_wojewodztwo_id'), 'powiat', ['wojewodztwo_id'], unique=False)
    op.create_table('gmina',
    sa.Column('nazwa', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('teryt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('powiat_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['powiat_id'], ['powiat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gmina_nazwa'), 'gmina', ['nazwa'], unique=False)
    op.create_index(op.f('ix_gmina_powiat_id'), 'gmina', ['powiat_id'], unique=False)
    op.create_index(op.f('ix_gmina_teryt'), 'gmina', ['teryt'], unique=True)
    op.create_table('miejscowosc',
    sa.Column('nazwa', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('teryt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gmina_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gmina_id'], ['gmina.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_miejscowosc_gmina_id'), 'miejscowosc', ['gmina_id'], unique=False)
    op.create_index(op.f('ix_miejscowosc_nazwa'), 'miejscowosc', ['nazwa'], unique=False)
    op.create_index(op.f('ix_miejscowosc_teryt'), 'miejscowosc', ['teryt'], unique=True)
    op.create_table('szkola',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('nazwa', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('numer_rspo', sa.Integer(), nullable=False),
    sa.Column('nazwa_skrocona', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('regon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('liczba_uczniow', sa.Integer(), nullable=True),
    sa.Column('dyrektor_imie', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dyrektor_nazwisko', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('kod_pocztowy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('numer_budynku', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('numer_lokalu', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('telefon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('strona_internetowa', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_zalozenia', sa.Date(), nullable=True),
    sa.Column('data_rozpoczecia', sa.Date(), nullable=True),
    sa.Column('data_likwidacji', sa.Date(), nullable=True),
    sa.Column('wynik', sa.Float(), nullable=True),
    sa.Column('zlikwidowana', sa.Boolean(), nullable=False),
    sa.Column('typ_id', sa.Integer(), nullable=True),
    sa.Column('status_publicznoprawny_id', sa.Integer(), nullable=True),
    sa.Column('kategoria_uczniow_id', sa.Integer(), nullable=True),
    sa.Column('miejscowosc_id', sa.Integer(), nullable=True),
    sa.Column('ulica_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('aktualna', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['kategoria_uczniow_id'], ['kategoria_uczniow.id'], ),
    sa.ForeignKeyConstraint(['miejscowosc_id'], ['miejscowosc.id'], ),
    sa.ForeignKeyConstraint(['status_publicznoprawny_id'], ['status_publicznoprawny.id'], ),
    sa.ForeignKeyConstraint(['typ_id'], ['typ_szkoly.id'], ),
    sa.ForeignKeyConstraint(['ulica_id'], ['ulica.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('regon')
    )
    op.create_index(op.f('ix_szkola_aktualna'), 'szkola', ['aktualna'], unique=False)
    op.create_index(op.f('ix_szkola_data_likwidacji'), 'szkola', ['data_likwidacji'], unique=False)
    op.create_index(op.f('ix_szkola_data_rozpoczecia'), 'szkola', ['data_rozpoczecia'], unique=False)
    op.create_index(op.f('ix_szkola_kategoria_uczniow_id'), 'szkola', ['kategoria_uczniow_id'], unique=False)
    op.create_index(op.f('ix_szkola_miejscowosc_id'), 'szkola', ['miejscowosc_id'], unique=False)
    op.create_index(op.f('ix_szkola_nazwa'), 'szkola', ['nazwa'], unique=False)
    op.create_index(op.f('ix_szkola_nazwa_skrocona'), 'szkola', ['nazwa_skrocona'], unique=False)
    op.create_index(op.f('ix_szkola_numer_rspo'), 'szkola', ['numer_rspo'], unique=True)
    op.create_index(op.f('ix_szkola_status_publicznoprawny_id'), 'szkola', ['status_publicznoprawny_id'], unique=False)
    op.create_index(op.f('ix_szkola_typ_id'), 'szkola', ['typ_id'], unique=False)
    op.create_index(op.f('ix_szkola_ulica_id'), 'szkola', ['ulica_id'], unique=False)
    op.create_index(op.f('ix_szkola_wynik'), 'szkola', ['wynik'], unique=False)
    op.create_index(op.f('ix_szkola_zlikwidowana'), 'szkola', ['zlikwidowana'], unique=False)
    op.create_table('szkolaetaplink',
    sa.Column('etap_id', sa.Integer(), nullable=False),
    sa.Column('szkola_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etap_id'], ['etap_edukacji.id'], ),
    sa.ForeignKeyConstraint(['szkola_id'], ['szkola.id'], ),
    sa.PrimaryKeyConstraint('etap_id', 'szkola_id')
    )
    op.create_table('szkolaksztalceniezawodowelink',
    sa.Column('ksztalcenie_zawodowe_id', sa.Integer(), nullable=False),
    sa.Column('szkola_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ksztalcenie_zawodowe_id'], ['ksztalcenie_zawodowe.id'], ),
    sa.ForeignKeyConstraint(['szkola_id'], ['szkola.id'], ),
    sa.PrimaryKeyConstraint('ksztalcenie_zawodowe_id', 'szkola_id')
    )
    op.create_table('wynik_e8',
    sa.Column('mediana', sa.Float(), nullable=True),
    sa.Column('szkola_id', sa.Integer(), nullable=False),
    sa.Column('przedmiot_id', sa.Integer(), nullable=False),
    sa.Column('rok', sa.Integer(), nullable=False),
    sa.Column('wynik_sredni', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('liczba_zdajacych', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['przedmiot_id'], ['przedmiot.id'], ),
    sa.ForeignKeyConstraint(['szkola_id'], ['szkola.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('szkola_id', 'przedmiot_id', 'rok', name='uq_wynik_e8_szkola_przedmiot_rok')
    )
    op.create_index(op.f('ix_wynik_e8_przedmiot_id'), 'wynik_e8', ['przedmiot_id'], unique=False)
    op.create_index(op.f('ix_wynik_e8_rok'), 'wynik_e8', ['rok'], unique=False)
    op.create_index(op.f('ix_wynik_e8_szkola_id'), 'wynik_e8', ['szkola_id'], unique=False)
    op.create_table('wynik_em',
    sa.Column('mediana', sa.Float(), nullable=True),
    sa.Column('szkola_id', sa.Integer(), nullable=False),
    sa.Column('przedmiot_id', sa.Integer(), nullable=False),
    sa.Column('rok', sa.Integer(), nullable=False),
    sa.Column('sredni_wynik', sa.Float(), nullable=True),
    sa.Column('zdawalnosc', sa.Float(), nullable=True),
    sa.Column('liczba_laureatow_finalistow', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('liczba_zdajacych', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['przedmiot_id'], ['przedmiot.id'], ),
    sa.ForeignKeyConstraint(['szkola_id'], ['szkola.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('szkola_id', 'przedmiot_id', 'rok', name='uq_wynik_em_szkola_przedmiot_rok')
    )
    op.create_index(op.f('ix_wynik_em_przedmiot_id'), 'wynik_em', ['przedmiot_id'], unique=False)
    op.create_index(op.f('ix_wynik_em_rok'), 'wynik_em', ['rok'], unique=False)
    op.create_index(op.f('ix_wynik_em_szkola_id'), 'wynik_em', ['szkola_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wynik_em_szkola_id'), table_name='wynik_em')
    op.drop_index(op.f('ix_wynik_em_rok'), table_name='wynik_em')
    op.drop_index(op.f('ix_wynik_em_przedmiot_id'), table_name='wynik_em')
    op.drop_table('wynik_em')
    op.drop_index(op.f('ix_wynik_e8_szkola_id'), table_name='wynik_e8')
    op.drop_index(op.f('ix_wynik_e8_rok'), table_name='wynik_e8')
    op.drop_index(op.f('ix_wynik_e8_przedmiot_id'), table_name='wynik_e8')
    op.drop_table('wynik_e8')
    op.drop_table('szkolaksztalceniezawodowelink')
    op.drop_table('szkolaetaplink')
    op.drop_index(op.f('ix_szkola_zlikwidowana'), table_name='szkola')
    op.drop_index(op.f('ix_szkola_wynik'), table_name='szkola')
    op.drop_index(op.f('ix_szkola_ulica_id'), table_name='szkola')
    op.drop_index(op.f('ix_szkola_typ_id'), table_name='szkola')
    op.drop_index(op.f('ix_szkola_status_publicznoprawny_id'), table_name='szkola')
    op.drop_index(op.f('ix_szkola_numer_rspo'), table_name='szkola')
    op.drop_index(op.f('ix_szkola_nazwa_skrocona'), table_name='szkola')
    op.drop_index(op.f('ix_szkola_nazwa'), table_name='szkola')
    op.drop_index(op.f('ix_szkola_miejscowosc_id'), table_name='szkola')
    op.drop_index(op.f('ix_szkola_kategoria_uczniow_id'), table_name='szkola')
    op.drop_index(op.f('ix_szkola_data_rozpoczecia'), table_name='szkola')
    op.drop_index(op.f('ix_szkola_data_likwidacji'), table_name='szkola')
    op.drop_index(op.f('ix_szkola_aktualna'), table_name='szkola')
    op.drop_table('szkola')
    op.drop_index(op.f('ix_miejscowosc_teryt'), table_name='miejscowosc')
    op.drop_index(op.f('ix_miejscowosc_nazwa'), table_name='miejscowosc')
    op.drop_index(op.f('ix_miejscowosc_gmina_id'), table_name='miejscowosc')
    op.drop_table('miejscowosc')
    op.drop_index(op.f('ix_gmina_teryt'), table_name='gmina')
    op.drop_index(op.f('ix_gmina_powiat_id'), table_name='gmina')
    op.drop_index(op.f('ix_gmina_nazwa'), table_name='gmina')
    op.drop_table('gmina')
    op.drop_index(op.f('ix_powiat_wojewodztwo_id'), table_name='powiat')
    op.drop_index(op.f('ix_powiat_teryt'), table_name='powiat')
    op.drop_index(op.f('ix_powiat_nazwa'), table_name='powiat')
    op.drop_table('powiat')
    op.drop_index(op.f('ix_wojewodztwo_teryt'), table_name='wojewodztwo')
    op.drop_index(op.f('ix_wojewodztwo_nazwa'), table_name='wojewodztwo')
    op.drop_table('wojewodztwo')
    op.drop_index(op.f('ix_ulica_teryt'), table_name='ulica')
    op.drop_index(op.f('ix_ulica_nazwa'), table_name='ulica')
    op.drop_table('ulica')
    op.drop_index(op.f('ix_typ_szkoly_nazwa'), table_name='typ_szkoly')
    op.drop_table('typ_szkoly')
    op.drop_index(op.f('ix_status_publicznoprawny_nazwa'), table_name='status_publicznoprawny')
    op.drop_table('status_publicznoprawny')
    op.drop_index(op.f('ix_przedmiot_nazwa'), table_name='przedmiot')
    op.drop_table('przedmiot')
    op.drop_index(op.f('ix_ksztalcenie_zawodowe_nazwa'), table_name='ksztalcenie_zawodowe')
    op.drop_table('ksztalcenie_zawodowe')
    op.drop_index(op.f('ix_kategoria_uczniow_nazwa'), table_name='kategoria_uczniow')
    op.drop_table('kategoria_uczniow')
    op.drop_index(op.f('ix_etap_edukacji_nazwa'), table_name='etap_edukacji')
    op.drop_table('etap_edukacji')
    # ### end Alembic commands ###
