"""add ranking table

Revision ID: f75febc5aa5a
Revises: fff7ba934856
Create Date: 2026-02-08 19:22:25.360750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f75febc5aa5a'
down_revision: Union[str, Sequence[str], None] = 'fff7ba934856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ranking',
    sa.Column('rok', sa.Integer(), nullable=False),
    sa.Column('rodzaj_rankingu', sa.Enum('E8', 'EM_LO', 'EM_TECH', name='rodzaj_rankingu'), nullable=False),
    sa.Column('wynik', sa.Float(), nullable=False),
    sa.Column('percentyl_kraj', sa.Float(), nullable=False),
    sa.Column('miejsce_kraj', sa.Integer(), nullable=False),
    sa.Column('liczba_szkol_kraj', sa.Integer(), nullable=False),
    sa.Column('percentyl_wojewodztwo', sa.Float(), nullable=False),
    sa.Column('miejsce_wojewodztwo', sa.Integer(), nullable=False),
    sa.Column('liczba_szkol_wojewodztwo', sa.Integer(), nullable=False),
    sa.Column('percentyl_powiat', sa.Float(), nullable=False),
    sa.Column('miejsce_powiat', sa.Integer(), nullable=False),
    sa.Column('liczba_szkol_powiat', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('szkola_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['szkola_id'], ['szkola.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('szkola_id', 'rok', 'rodzaj_rankingu', name='uq_ranking_szkola_rok_rodzaj')
    )
    op.create_index(op.f('ix_ranking_miejsce_kraj'), 'ranking', ['miejsce_kraj'], unique=False)
    op.create_index(op.f('ix_ranking_miejsce_powiat'), 'ranking', ['miejsce_powiat'], unique=False)
    op.create_index(op.f('ix_ranking_miejsce_wojewodztwo'), 'ranking', ['miejsce_wojewodztwo'], unique=False)
    op.create_index(op.f('ix_ranking_percentyl_kraj'), 'ranking', ['percentyl_kraj'], unique=False)
    op.create_index(op.f('ix_ranking_percentyl_powiat'), 'ranking', ['percentyl_powiat'], unique=False)
    op.create_index(op.f('ix_ranking_percentyl_wojewodztwo'), 'ranking', ['percentyl_wojewodztwo'], unique=False)
    op.create_index(op.f('ix_ranking_rodzaj_rankingu'), 'ranking', ['rodzaj_rankingu'], unique=False)
    op.create_index(op.f('ix_ranking_rok'), 'ranking', ['rok'], unique=False)
    op.create_index(op.f('ix_ranking_szkola_id'), 'ranking', ['szkola_id'], unique=False)
    op.create_index(op.f('ix_ranking_wynik'), 'ranking', ['wynik'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ranking_wynik'), table_name='ranking')
    op.drop_index(op.f('ix_ranking_szkola_id'), table_name='ranking')
    op.drop_index(op.f('ix_ranking_rok'), table_name='ranking')
    op.drop_index(op.f('ix_ranking_rodzaj_rankingu'), table_name='ranking')
    op.drop_index(op.f('ix_ranking_percentyl_wojewodztwo'), table_name='ranking')
    op.drop_index(op.f('ix_ranking_percentyl_powiat'), table_name='ranking')
    op.drop_index(op.f('ix_ranking_percentyl_kraj'), table_name='ranking')
    op.drop_index(op.f('ix_ranking_miejsce_wojewodztwo'), table_name='ranking')
    op.drop_index(op.f('ix_ranking_miejsce_powiat'), table_name='ranking')
    op.drop_index(op.f('ix_ranking_miejsce_kraj'), table_name='ranking')
    op.drop_table('ranking')
    # ### end Alembic commands ###
